title: Epicycle.Input (.NET)
url: https://github.com/open-epicycle/Epicycle.Geodesy-cs
summary: "Epicycle .NET input library. Includes: keyboard abstraction and keyboard state machines, sensor abstraction, sensor simulation and recording play-back"

organization: Epicycle
tags: epicycle lib library input keyboard sensor sensors simulation playback
copyright: Copyright 2015 Epicycle
license_url: http://www.apache.org/licenses/LICENSE-2.0

release_notes: https://github.com/open-epicycle/Epicycle.Input-cs/blob/ver-$version$/README.md

dotnet_frameworks:
 - net35
 - net40
 - net45

nuget_dependencies:
 - Epicycle.Commons-cs.0.1.8.0
 - Epicycle.Math-cs.0.1.6.0
 - Epicycle.Geodesy-cs.0.1.4.0

description: |
   Epicycle .NET input library. Includes: keyboard abstraction and keyboard state machines, sensor abstraction, sensor simulation and recording play-back
   
   * Details & release notes: https://github.com/open-epicycle/Epicycle.Input-cs/blob/ver-$version$/README.md
   * Sources: https://github.com/open-epicycle/Epicycle.Input-cs/tree/ver-$version$
   * Git repository: https://github.com/open-epicycle/Epicycle.Input-cs